package hiben;
// Generated Dec 20, 2015 7:01:48 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Brand generated by hbm2java
 */
public class Brand  implements java.io.Serializable {


     private Integer idbrand;
     private String brandName;
     private Set<Products> productses = new HashSet<Products>(0);

    public Brand() {
    }

    public Brand(String brandName, Set<Products> productses) {
       this.brandName = brandName;
       this.productses = productses;
    }
   
    public Integer getIdbrand() {
        return this.idbrand;
    }
    
    public void setIdbrand(Integer idbrand) {
        this.idbrand = idbrand;
    }
    public String getBrandName() {
        return this.brandName;
    }
    
    public void setBrandName(String brandName) {
        this.brandName = brandName;
    }
    public Set<Products> getProductses() {
        return this.productses;
    }
    
    public void setProductses(Set<Products> productses) {
        this.productses = productses;
    }




}


