package hiben;
// Generated Dec 20, 2015 7:01:48 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cart generated by hbm2java
 */
public class Cart  implements java.io.Serializable {


     private Integer idcart;
     private User user;
     private Integer totProd;
     private Double totVal;
     private Set<CartProd> cartProds = new HashSet<CartProd>(0);

    public Cart() {
    }

	
    public Cart(User user) {
        this.user = user;
    }
    public Cart(User user, Integer totProd, Double totVal, Set<CartProd> cartProds) {
       this.user = user;
       this.totProd = totProd;
       this.totVal = totVal;
       this.cartProds = cartProds;
    }
   
    public Integer getIdcart() {
        return this.idcart;
    }
    
    public void setIdcart(Integer idcart) {
        this.idcart = idcart;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Integer getTotProd() {
        return this.totProd;
    }
    
    public void setTotProd(Integer totProd) {
        this.totProd = totProd;
    }
    public Double getTotVal() {
        return this.totVal;
    }
    
    public void setTotVal(Double totVal) {
        this.totVal = totVal;
    }
    public Set<CartProd> getCartProds() {
        return this.cartProds;
    }
    
    public void setCartProds(Set<CartProd> cartProds) {
        this.cartProds = cartProds;
    }




}


