package hiben;
// Generated Dec 20, 2015 7:01:48 PM by Hibernate Tools 4.3.1



/**
 * CartProd generated by hbm2java
 */
public class CartProd  implements java.io.Serializable {


     private Integer idcartProd;
     private Cart cart;
     private Stock stock;
     private Integer qty;
     private Integer isPurches;

    public CartProd() {
    }

	
    public CartProd(Cart cart, Stock stock) {
        this.cart = cart;
        this.stock = stock;
    }
    public CartProd(Cart cart, Stock stock, Integer qty, Integer isPurches) {
       this.cart = cart;
       this.stock = stock;
       this.qty = qty;
       this.isPurches = isPurches;
    }
   
    public Integer getIdcartProd() {
        return this.idcartProd;
    }
    
    public void setIdcartProd(Integer idcartProd) {
        this.idcartProd = idcartProd;
    }
    public Cart getCart() {
        return this.cart;
    }
    
    public void setCart(Cart cart) {
        this.cart = cart;
    }
    public Stock getStock() {
        return this.stock;
    }
    
    public void setStock(Stock stock) {
        this.stock = stock;
    }
    public Integer getQty() {
        return this.qty;
    }
    
    public void setQty(Integer qty) {
        this.qty = qty;
    }
    public Integer getIsPurches() {
        return this.isPurches;
    }
    
    public void setIsPurches(Integer isPurches) {
        this.isPurches = isPurches;
    }




}


