package hiben;
// Generated Dec 20, 2015 7:01:48 PM by Hibernate Tools 4.3.1



/**
 * Interfaces generated by hbm2java
 */
public class Interfaces  implements java.io.Serializable {


     private Integer idinterfaces;
     private IntfGroup intfGroup;
     private String ifaseName;
     private String url;

    public Interfaces() {
    }

	
    public Interfaces(IntfGroup intfGroup) {
        this.intfGroup = intfGroup;
    }
    public Interfaces(IntfGroup intfGroup, String ifaseName, String url) {
       this.intfGroup = intfGroup;
       this.ifaseName = ifaseName;
       this.url = url;
    }
   
    public Integer getIdinterfaces() {
        return this.idinterfaces;
    }
    
    public void setIdinterfaces(Integer idinterfaces) {
        this.idinterfaces = idinterfaces;
    }
    public IntfGroup getIntfGroup() {
        return this.intfGroup;
    }
    
    public void setIntfGroup(IntfGroup intfGroup) {
        this.intfGroup = intfGroup;
    }
    public String getIfaseName() {
        return this.ifaseName;
    }
    
    public void setIfaseName(String ifaseName) {
        this.ifaseName = ifaseName;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }




}


