package hiben;
// Generated Dec 20, 2015 7:01:48 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Invoice generated by hbm2java
 */
public class Invoice  implements java.io.Serializable {


     private Integer idinvoice;
     private Transaction transaction;
     private String invoiceNo;
     private Date invoiceDate;
     private Double amount;
     private Double paid;

    public Invoice() {
    }

	
    public Invoice(Transaction transaction, Date invoiceDate) {
        this.transaction = transaction;
        this.invoiceDate = invoiceDate;
    }
    public Invoice(Transaction transaction, String invoiceNo, Date invoiceDate, Double amount, Double paid) {
       this.transaction = transaction;
       this.invoiceNo = invoiceNo;
       this.invoiceDate = invoiceDate;
       this.amount = amount;
       this.paid = paid;
    }
   
    public Integer getIdinvoice() {
        return this.idinvoice;
    }
    
    public void setIdinvoice(Integer idinvoice) {
        this.idinvoice = idinvoice;
    }
    public Transaction getTransaction() {
        return this.transaction;
    }
    
    public void setTransaction(Transaction transaction) {
        this.transaction = transaction;
    }
    public String getInvoiceNo() {
        return this.invoiceNo;
    }
    
    public void setInvoiceNo(String invoiceNo) {
        this.invoiceNo = invoiceNo;
    }
    public Date getInvoiceDate() {
        return this.invoiceDate;
    }
    
    public void setInvoiceDate(Date invoiceDate) {
        this.invoiceDate = invoiceDate;
    }
    public Double getAmount() {
        return this.amount;
    }
    
    public void setAmount(Double amount) {
        this.amount = amount;
    }
    public Double getPaid() {
        return this.paid;
    }
    
    public void setPaid(Double paid) {
        this.paid = paid;
    }




}


