package hiben;
// Generated Dec 20, 2015 7:01:48 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * LoginSession generated by hbm2java
 */
public class LoginSession  implements java.io.Serializable {


     private Integer idloginSession;
     private User user;
     private String ipAdd;
     private Date loginTime;

    public LoginSession() {
    }

    public LoginSession(User user, String ipAdd, Date loginTime) {
       this.user = user;
       this.ipAdd = ipAdd;
       this.loginTime = loginTime;
    }
   
    public Integer getIdloginSession() {
        return this.idloginSession;
    }
    
    public void setIdloginSession(Integer idloginSession) {
        this.idloginSession = idloginSession;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getIpAdd() {
        return this.ipAdd;
    }
    
    public void setIpAdd(String ipAdd) {
        this.ipAdd = ipAdd;
    }
    public Date getLoginTime() {
        return this.loginTime;
    }
    
    public void setLoginTime(Date loginTime) {
        this.loginTime = loginTime;
    }




}


