package hiben;
// Generated Dec 20, 2015 7:01:48 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * PaymentMethod generated by hbm2java
 */
public class PaymentMethod  implements java.io.Serializable {


     private Integer idpmethod;
     private String method;
     private Set<Transaction> transactions = new HashSet<Transaction>(0);

    public PaymentMethod() {
    }

    public PaymentMethod(String method, Set<Transaction> transactions) {
       this.method = method;
       this.transactions = transactions;
    }
   
    public Integer getIdpmethod() {
        return this.idpmethod;
    }
    
    public void setIdpmethod(Integer idpmethod) {
        this.idpmethod = idpmethod;
    }
    public String getMethod() {
        return this.method;
    }
    
    public void setMethod(String method) {
        this.method = method;
    }
    public Set<Transaction> getTransactions() {
        return this.transactions;
    }
    
    public void setTransactions(Set<Transaction> transactions) {
        this.transactions = transactions;
    }




}


