package hiben;
// Generated Dec 20, 2015 7:01:48 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * PersonalDetails generated by hbm2java
 */
public class PersonalDetails  implements java.io.Serializable {


     private Integer idpdetails;
     private Address address;
     private String FName;
     private String LName;
     private String phone;
     private Set<User> users = new HashSet<User>(0);

    public PersonalDetails() {
    }

	
    public PersonalDetails(Address address) {
        this.address = address;
    }
    public PersonalDetails(Address address, String FName, String LName, String phone, Set<User> users) {
       this.address = address;
       this.FName = FName;
       this.LName = LName;
       this.phone = phone;
       this.users = users;
    }
   
    public Integer getIdpdetails() {
        return this.idpdetails;
    }
    
    public void setIdpdetails(Integer idpdetails) {
        this.idpdetails = idpdetails;
    }
    public Address getAddress() {
        return this.address;
    }
    
    public void setAddress(Address address) {
        this.address = address;
    }
    public String getFName() {
        return this.FName;
    }
    
    public void setFName(String FName) {
        this.FName = FName;
    }
    public String getLName() {
        return this.LName;
    }
    
    public void setLName(String LName) {
        this.LName = LName;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public Set<User> getUsers() {
        return this.users;
    }
    
    public void setUsers(Set<User> users) {
        this.users = users;
    }




}


