package hiben;
// Generated Dec 20, 2015 7:01:48 PM by Hibernate Tools 4.3.1



/**
 * Privilage generated by hbm2java
 */
public class Privilage  implements java.io.Serializable {


     private Integer idprivilage;
     private IntfGroup intfGroup;
     private UserType userType;

    public Privilage() {
    }

    public Privilage(IntfGroup intfGroup, UserType userType) {
       this.intfGroup = intfGroup;
       this.userType = userType;
    }
   
    public Integer getIdprivilage() {
        return this.idprivilage;
    }
    
    public void setIdprivilage(Integer idprivilage) {
        this.idprivilage = idprivilage;
    }
    public IntfGroup getIntfGroup() {
        return this.intfGroup;
    }
    
    public void setIntfGroup(IntfGroup intfGroup) {
        this.intfGroup = intfGroup;
    }
    public UserType getUserType() {
        return this.userType;
    }
    
    public void setUserType(UserType userType) {
        this.userType = userType;
    }




}


