package hiben;
// Generated Dec 20, 2015 7:01:48 PM by Hibernate Tools 4.3.1



/**
 * ProdHasProp generated by hbm2java
 */
public class ProdHasProp  implements java.io.Serializable {


     private Integer phpid;
     private ProdProperty prodProperty;
     private Products products;
     private String value;

    public ProdHasProp() {
    }

	
    public ProdHasProp(ProdProperty prodProperty, Products products) {
        this.prodProperty = prodProperty;
        this.products = products;
    }
    public ProdHasProp(ProdProperty prodProperty, Products products, String value) {
       this.prodProperty = prodProperty;
       this.products = products;
       this.value = value;
    }
   
    public Integer getPhpid() {
        return this.phpid;
    }
    
    public void setPhpid(Integer phpid) {
        this.phpid = phpid;
    }
    public ProdProperty getProdProperty() {
        return this.prodProperty;
    }
    
    public void setProdProperty(ProdProperty prodProperty) {
        this.prodProperty = prodProperty;
    }
    public Products getProducts() {
        return this.products;
    }
    
    public void setProducts(Products products) {
        this.products = products;
    }
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }




}


