package hiben;
// Generated Dec 20, 2015 7:01:48 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Products generated by hbm2java
 */
public class Products  implements java.io.Serializable {


     private Integer itmCode;
     private Brand brand;
     private Category category;
     private String prodCode;
     private String itmName;
     private Integer reorderLevel;
     private Integer active;
     private String imgUrl;
     private Set<Stock> stocks = new HashSet<Stock>(0);
     private Set<ProdHasProp> prodHasProps = new HashSet<ProdHasProp>(0);

    public Products() {
    }

	
    public Products(Brand brand, Category category, String prodCode) {
        this.brand = brand;
        this.category = category;
        this.prodCode = prodCode;
    }
    public Products(Brand brand, Category category, String prodCode, String itmName, Integer reorderLevel, Integer active, String imgUrl, Set<Stock> stocks, Set<ProdHasProp> prodHasProps) {
       this.brand = brand;
       this.category = category;
       this.prodCode = prodCode;
       this.itmName = itmName;
       this.reorderLevel = reorderLevel;
       this.active = active;
       this.imgUrl = imgUrl;
       this.stocks = stocks;
       this.prodHasProps = prodHasProps;
    }
   
    public Integer getItmCode() {
        return this.itmCode;
    }
    
    public void setItmCode(Integer itmCode) {
        this.itmCode = itmCode;
    }
    public Brand getBrand() {
        return this.brand;
    }
    
    public void setBrand(Brand brand) {
        this.brand = brand;
    }
    public Category getCategory() {
        return this.category;
    }
    
    public void setCategory(Category category) {
        this.category = category;
    }
    public String getProdCode() {
        return this.prodCode;
    }
    
    public void setProdCode(String prodCode) {
        this.prodCode = prodCode;
    }
    public String getItmName() {
        return this.itmName;
    }
    
    public void setItmName(String itmName) {
        this.itmName = itmName;
    }
    public Integer getReorderLevel() {
        return this.reorderLevel;
    }
    
    public void setReorderLevel(Integer reorderLevel) {
        this.reorderLevel = reorderLevel;
    }
    public Integer getActive() {
        return this.active;
    }
    
    public void setActive(Integer active) {
        this.active = active;
    }
    public String getImgUrl() {
        return this.imgUrl;
    }
    
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl;
    }
    public Set<Stock> getStocks() {
        return this.stocks;
    }
    
    public void setStocks(Set<Stock> stocks) {
        this.stocks = stocks;
    }
    public Set<ProdHasProp> getProdHasProps() {
        return this.prodHasProps;
    }
    
    public void setProdHasProps(Set<ProdHasProp> prodHasProps) {
        this.prodHasProps = prodHasProps;
    }




}


