package hiben;
// Generated Dec 20, 2015 7:01:48 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * PropertyGroup generated by hbm2java
 */
public class PropertyGroup  implements java.io.Serializable {


     private Integer idproGrop;
     private String groupName;
     private Set<ProdProperty> prodProperties = new HashSet<ProdProperty>(0);

    public PropertyGroup() {
    }

    public PropertyGroup(String groupName, Set<ProdProperty> prodProperties) {
       this.groupName = groupName;
       this.prodProperties = prodProperties;
    }
   
    public Integer getIdproGrop() {
        return this.idproGrop;
    }
    
    public void setIdproGrop(Integer idproGrop) {
        this.idproGrop = idproGrop;
    }
    public String getGroupName() {
        return this.groupName;
    }
    
    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }
    public Set<ProdProperty> getProdProperties() {
        return this.prodProperties;
    }
    
    public void setProdProperties(Set<ProdProperty> prodProperties) {
        this.prodProperties = prodProperties;
    }




}


