package hiben;
// Generated Dec 20, 2015 7:01:48 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Stock generated by hbm2java
 */
public class Stock  implements java.io.Serializable {


     private Integer batchid;
     private Products products;
     private Double itmPrice;
     private Integer quentity;
     private Double discount;
     private String color;
     private Integer storage;
     private Date stockDate;
     private Set<TransProd> transProds = new HashSet<TransProd>(0);
     private Set<WishProd> wishProds = new HashSet<WishProd>(0);
     private Set<CartProd> cartProds = new HashSet<CartProd>(0);

    public Stock() {
    }

	
    public Stock(Products products, Date stockDate) {
        this.products = products;
        this.stockDate = stockDate;
    }
    public Stock(Products products, Double itmPrice, Integer quentity, Double discount, String color, Integer storage, Date stockDate, Set<TransProd> transProds, Set<WishProd> wishProds, Set<CartProd> cartProds) {
       this.products = products;
       this.itmPrice = itmPrice;
       this.quentity = quentity;
       this.discount = discount;
       this.color = color;
       this.storage = storage;
       this.stockDate = stockDate;
       this.transProds = transProds;
       this.wishProds = wishProds;
       this.cartProds = cartProds;
    }
   
    public Integer getBatchid() {
        return this.batchid;
    }
    
    public void setBatchid(Integer batchid) {
        this.batchid = batchid;
    }
    public Products getProducts() {
        return this.products;
    }
    
    public void setProducts(Products products) {
        this.products = products;
    }
    public Double getItmPrice() {
        return this.itmPrice;
    }
    
    public void setItmPrice(Double itmPrice) {
        this.itmPrice = itmPrice;
    }
    public Integer getQuentity() {
        return this.quentity;
    }
    
    public void setQuentity(Integer quentity) {
        this.quentity = quentity;
    }
    public Double getDiscount() {
        return this.discount;
    }
    
    public void setDiscount(Double discount) {
        this.discount = discount;
    }
    public String getColor() {
        return this.color;
    }
    
    public void setColor(String color) {
        this.color = color;
    }
    public Integer getStorage() {
        return this.storage;
    }
    
    public void setStorage(Integer storage) {
        this.storage = storage;
    }
    public Date getStockDate() {
        return this.stockDate;
    }
    
    public void setStockDate(Date stockDate) {
        this.stockDate = stockDate;
    }
    public Set<TransProd> getTransProds() {
        return this.transProds;
    }
    
    public void setTransProds(Set<TransProd> transProds) {
        this.transProds = transProds;
    }
    public Set<WishProd> getWishProds() {
        return this.wishProds;
    }
    
    public void setWishProds(Set<WishProd> wishProds) {
        this.wishProds = wishProds;
    }
    public Set<CartProd> getCartProds() {
        return this.cartProds;
    }
    
    public void setCartProds(Set<CartProd> cartProds) {
        this.cartProds = cartProds;
    }




}


