package hiben;
// Generated Dec 20, 2015 7:01:48 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Transaction generated by hbm2java
 */
public class Transaction  implements java.io.Serializable {


     private Integer idtransaction;
     private PaymentMethod paymentMethod;
     private User user;
     private Double totAmount;
     private Integer totItms;
     private Double shipingCost;
     private Date transDate;
     private Integer isSend;
     private Set<Invoice> invoices = new HashSet<Invoice>(0);
     private Set<TransProd> transProds = new HashSet<TransProd>(0);

    public Transaction() {
    }

	
    public Transaction(User user, Date transDate) {
        this.user = user;
        this.transDate = transDate;
    }
    public Transaction(PaymentMethod paymentMethod, User user, Double totAmount, Integer totItms, Double shipingCost, Date transDate, Integer isSend, Set<Invoice> invoices, Set<TransProd> transProds) {
       this.paymentMethod = paymentMethod;
       this.user = user;
       this.totAmount = totAmount;
       this.totItms = totItms;
       this.shipingCost = shipingCost;
       this.transDate = transDate;
       this.isSend = isSend;
       this.invoices = invoices;
       this.transProds = transProds;
    }
   
    public Integer getIdtransaction() {
        return this.idtransaction;
    }
    
    public void setIdtransaction(Integer idtransaction) {
        this.idtransaction = idtransaction;
    }
    public PaymentMethod getPaymentMethod() {
        return this.paymentMethod;
    }
    
    public void setPaymentMethod(PaymentMethod paymentMethod) {
        this.paymentMethod = paymentMethod;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Double getTotAmount() {
        return this.totAmount;
    }
    
    public void setTotAmount(Double totAmount) {
        this.totAmount = totAmount;
    }
    public Integer getTotItms() {
        return this.totItms;
    }
    
    public void setTotItms(Integer totItms) {
        this.totItms = totItms;
    }
    public Double getShipingCost() {
        return this.shipingCost;
    }
    
    public void setShipingCost(Double shipingCost) {
        this.shipingCost = shipingCost;
    }
    public Date getTransDate() {
        return this.transDate;
    }
    
    public void setTransDate(Date transDate) {
        this.transDate = transDate;
    }
    public Integer getIsSend() {
        return this.isSend;
    }
    
    public void setIsSend(Integer isSend) {
        this.isSend = isSend;
    }
    public Set<Invoice> getInvoices() {
        return this.invoices;
    }
    
    public void setInvoices(Set<Invoice> invoices) {
        this.invoices = invoices;
    }
    public Set<TransProd> getTransProds() {
        return this.transProds;
    }
    
    public void setTransProds(Set<TransProd> transProds) {
        this.transProds = transProds;
    }




}


