package hiben;
// Generated Dec 20, 2015 7:01:48 PM by Hibernate Tools 4.3.1



/**
 * TransProd generated by hbm2java
 */
public class TransProd  implements java.io.Serializable {


     private Integer idtransProd;
     private Stock stock;
     private Transaction transaction;
     private Double itmPrice;
     private Double soldPrice;
     private Double discount;
     private Integer qty;

    public TransProd() {
    }

	
    public TransProd(Stock stock, Transaction transaction) {
        this.stock = stock;
        this.transaction = transaction;
    }
    public TransProd(Stock stock, Transaction transaction, Double itmPrice, Double soldPrice, Double discount, Integer qty) {
       this.stock = stock;
       this.transaction = transaction;
       this.itmPrice = itmPrice;
       this.soldPrice = soldPrice;
       this.discount = discount;
       this.qty = qty;
    }
   
    public Integer getIdtransProd() {
        return this.idtransProd;
    }
    
    public void setIdtransProd(Integer idtransProd) {
        this.idtransProd = idtransProd;
    }
    public Stock getStock() {
        return this.stock;
    }
    
    public void setStock(Stock stock) {
        this.stock = stock;
    }
    public Transaction getTransaction() {
        return this.transaction;
    }
    
    public void setTransaction(Transaction transaction) {
        this.transaction = transaction;
    }
    public Double getItmPrice() {
        return this.itmPrice;
    }
    
    public void setItmPrice(Double itmPrice) {
        this.itmPrice = itmPrice;
    }
    public Double getSoldPrice() {
        return this.soldPrice;
    }
    
    public void setSoldPrice(Double soldPrice) {
        this.soldPrice = soldPrice;
    }
    public Double getDiscount() {
        return this.discount;
    }
    
    public void setDiscount(Double discount) {
        this.discount = discount;
    }
    public Integer getQty() {
        return this.qty;
    }
    
    public void setQty(Integer qty) {
        this.qty = qty;
    }




}


