package hiben;
// Generated Dec 20, 2015 7:01:48 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * UserType generated by hbm2java
 */
public class UserType  implements java.io.Serializable {


     private Integer guestId;
     private String type;
     private Set<User> users = new HashSet<User>(0);
     private Set<Privilage> privilages = new HashSet<Privilage>(0);

    public UserType() {
    }

    public UserType(String type, Set<User> users, Set<Privilage> privilages) {
       this.type = type;
       this.users = users;
       this.privilages = privilages;
    }
   
    public Integer getGuestId() {
        return this.guestId;
    }
    
    public void setGuestId(Integer guestId) {
        this.guestId = guestId;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public Set<User> getUsers() {
        return this.users;
    }
    
    public void setUsers(Set<User> users) {
        this.users = users;
    }
    public Set<Privilage> getPrivilages() {
        return this.privilages;
    }
    
    public void setPrivilages(Set<Privilage> privilages) {
        this.privilages = privilages;
    }




}


