package hiben;
// Generated Dec 20, 2015 7:01:48 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer userId;
     private PersonalDetails personalDetails;
     private UserType userType;
     private String email;
     private String password;
     private Date createTime;
     private String verifyCode;
     private String nic;
     private Set<Transaction> transactions = new HashSet<Transaction>(0);
     private Set<Cart> carts = new HashSet<Cart>(0);
     private Set<LoginSession> loginSessions = new HashSet<LoginSession>(0);
     private Set<Wishlist> wishlists = new HashSet<Wishlist>(0);

    public User() {
    }

	
    public User(PersonalDetails personalDetails, UserType userType, String email, String password, Date createTime) {
        this.personalDetails = personalDetails;
        this.userType = userType;
        this.email = email;
        this.password = password;
        this.createTime = createTime;
    }
    public User(PersonalDetails personalDetails, UserType userType, String email, String password, Date createTime, String verifyCode, String nic, Set<Transaction> transactions, Set<Cart> carts, Set<LoginSession> loginSessions, Set<Wishlist> wishlists) {
       this.personalDetails = personalDetails;
       this.userType = userType;
       this.email = email;
       this.password = password;
       this.createTime = createTime;
       this.verifyCode = verifyCode;
       this.nic = nic;
       this.transactions = transactions;
       this.carts = carts;
       this.loginSessions = loginSessions;
       this.wishlists = wishlists;
    }
   
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    public PersonalDetails getPersonalDetails() {
        return this.personalDetails;
    }
    
    public void setPersonalDetails(PersonalDetails personalDetails) {
        this.personalDetails = personalDetails;
    }
    public UserType getUserType() {
        return this.userType;
    }
    
    public void setUserType(UserType userType) {
        this.userType = userType;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
    public String getVerifyCode() {
        return this.verifyCode;
    }
    
    public void setVerifyCode(String verifyCode) {
        this.verifyCode = verifyCode;
    }
    public String getNic() {
        return this.nic;
    }
    
    public void setNic(String nic) {
        this.nic = nic;
    }
    public Set<Transaction> getTransactions() {
        return this.transactions;
    }
    
    public void setTransactions(Set<Transaction> transactions) {
        this.transactions = transactions;
    }
    public Set<Cart> getCarts() {
        return this.carts;
    }
    
    public void setCarts(Set<Cart> carts) {
        this.carts = carts;
    }
    public Set<LoginSession> getLoginSessions() {
        return this.loginSessions;
    }
    
    public void setLoginSessions(Set<LoginSession> loginSessions) {
        this.loginSessions = loginSessions;
    }
    public Set<Wishlist> getWishlists() {
        return this.wishlists;
    }
    
    public void setWishlists(Set<Wishlist> wishlists) {
        this.wishlists = wishlists;
    }




}


