package hiben;
// Generated Dec 20, 2015 7:01:48 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Wishlist generated by hbm2java
 */
public class Wishlist  implements java.io.Serializable {


     private Integer idwishlist;
     private User user;
     private Integer totProd;
     private Set<WishProd> wishProds = new HashSet<WishProd>(0);

    public Wishlist() {
    }

	
    public Wishlist(User user) {
        this.user = user;
    }
    public Wishlist(User user, Integer totProd, Set<WishProd> wishProds) {
       this.user = user;
       this.totProd = totProd;
       this.wishProds = wishProds;
    }
   
    public Integer getIdwishlist() {
        return this.idwishlist;
    }
    
    public void setIdwishlist(Integer idwishlist) {
        this.idwishlist = idwishlist;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Integer getTotProd() {
        return this.totProd;
    }
    
    public void setTotProd(Integer totProd) {
        this.totProd = totProd;
    }
    public Set<WishProd> getWishProds() {
        return this.wishProds;
    }
    
    public void setWishProds(Set<WishProd> wishProds) {
        this.wishProds = wishProds;
    }




}


