package hiben;
// Generated Dec 20, 2015 7:01:48 PM by Hibernate Tools 4.3.1



/**
 * WishProd generated by hbm2java
 */
public class WishProd  implements java.io.Serializable {


     private Integer idwishProd;
     private Stock stock;
     private Wishlist wishlist;

    public WishProd() {
    }

    public WishProd(Stock stock, Wishlist wishlist) {
       this.stock = stock;
       this.wishlist = wishlist;
    }
   
    public Integer getIdwishProd() {
        return this.idwishProd;
    }
    
    public void setIdwishProd(Integer idwishProd) {
        this.idwishProd = idwishProd;
    }
    public Stock getStock() {
        return this.stock;
    }
    
    public void setStock(Stock stock) {
        this.stock = stock;
    }
    public Wishlist getWishlist() {
        return this.wishlist;
    }
    
    public void setWishlist(Wishlist wishlist) {
        this.wishlist = wishlist;
    }




}


